### ISSUE TITLE
使用登记 / Who's using Cardinal?

### ISSUE THREAD

**Issue by wuhan005** [vidar-team/Cardinal#105]
首先诚挚地感谢每一位持续关注并使用 Cardinal 的朋友。
我们会持续投入，力图把 Cardinal 变得更好。
为了更好的聆听大家的声音，吸引更多的人使用和参与，我们期待您在此提交一条评论。

您可以参考下面的样例来提供您的信息：
团队：Vidar-Team
链接：https://vidar.club/ （方便获取 Logo）
场景：战队内 AWD 训练

感谢您的参与！！！

**Comment by PolarPeak** [comment]
团队：齐鲁师范学院网络安全社团
场景：社团内 AWD 训练

**Comment by Roooodie** [comment]
Hi, i hope it's not that rare to see english comment 😁 ...  Yes, i'm currently testing out this framework ... Which is so cool tbh. it's very rare to have "easy to install" framework like yours in A/D or AWD CTF ... I've been trying to find how to properly contact the team for some permission things and issues i had, but it's hard for me since our language barrier (luckily there is google-translate for me to use to translate all the documentation) ... Thank you so much, great work there

**Comment by wuhan005** [comment]
> Hi, i hope it's not that rare to see english comment 😁 ... Yes, i'm currently testing out this framework ... Which is so cool tbh. it's very rare to have "easy to install" framework like yours in A/D or AWD CTF ... I've been trying to find how to properly contact the team for some permission things and issues i had, but it's hard for me since our language barrier (luckily there is google-translate for me to use to translate all the documentation) ... Thank you so much, great work there

Thanks for your support! If you meet any problems when using Cardinal, you can [create an new issue](https://github.com/vidar-team/Cardinal/issues/new). English is ok.

By the way, we will publish the English documentations soon. Sorry for the confusion.
