### ISSUE TITLE
如何一键重置队伍分数？

### ISSUE THREAD

**Issue by teawaterwu** [vidar-team/Cardinal#92]
正常情况下要清空队伍分数，每次要重新部署队伍和靶机比较麻烦，请教有没有比较方便的方法重置所有队伍的分数？我改了数据库的teams表，但是不起作用，分数会恢复。

**Comment by wuhan005** [comment]
目前重置队伍分数的办法，是手动删除数据库中的`attack_actions`和`down_actions`两张表的内容，重启平台后将会重新算分。

重置所有队伍分数这个需求了解了，之后的版本更新会考虑加入。

**Comment by teawaterwu** [comment]
感谢您的回复，请问是把这两张表内容全删吗？

**Comment by wuhan005** [comment]
对 清除两张表的数据或者直接删除两张表都可。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: teawaterwu <notifications@github.com&gt;
发送时间: 2020年11月30日 18:36
收件人: vidar-team/Cardinal <Cardinal@noreply.github.com&gt;
抄送: E99p1ant <524306184@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[vidar-team/Cardinal] 如何一键重置队伍分数？ (#92)





 感谢您的回复，请问是把这两张表内容全删吗？ 
 
 &gt; 在 2020年11月30日，下午5:57，E99p1ant <notifications@github.com&gt; 写道： 
 &gt;  
 &gt; ﻿ 
 &gt; 目前重置队伍分数的办法，是手动删除数据库中的attack_actions和down_actions两张表的内容，重启平台后将会重新算分。 
 &gt;  
 &gt; 重置所有队伍分数这个需求了解了，之后的版本更新会考虑加入。 
 &gt;  
 &gt; — 
 &gt; You are receiving this because you authored the thread. 
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by wuhan005** [comment]
一键重置队伍分数功能已在 [v0.7.3 版本](https://github.com/vidar-team/Cardinal/releases/tag/v0.7.3) 加入。

在`靶机管理`页面点击`重置所有靶机分数`即可。
